ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'USER_CREATED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'USER_UPDATED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'USER_STATUS_CHANGED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'USER_ROLE_CHANGED';
